//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursa4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bike
    {
        public int id { get; set; }
        public int NumberBike { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Size { get; set; }
        public string Material { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<int> Picture { get; set; }
        public byte[] Image { get; set; }
    }
}
